GET http://localhost:8000/api/users


###
POST http://localhost:8000/api/users
Content-Type: application/json

{
  "name": "kuku",
  "email": "kuku@example.com"
}


###
PUT http://localhost:8000/api/users/1
Content-Type: application/json

{
  "name": "updated test",
  "email": "updated@example.com"
}



###
DELETE http://localhost:8000/api/users/1